macro( use_cxx11 )
  if ( CMAKE_VERSION VERSION_LESS "4.6" )
    include( CheckCXXCompilerFlag )
    CHECK_CXX_COMPILER_FLAG( "-std=c++11" COMPILER_SUPPORTS_CXX11 )
    if( COMPILER_SUPPORTS_CXX11 )
      set( CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11" )
    else()
      message( FATAL_ERROR "The compiler ${CMAKE_CXX_COMPILER} has no C++11 support. Please use a different C++ compiler." )
    endif()
  else()
    set ( CMAKE_CXX_STANDARD_REQUIRED ON )
    set ( CMAKE_CXX_STANDARD 11 )
  endif ()
endmacro( use_cxx11 )
